# 4-1
CREATE TABLE user (
                      id BIGINT AUTO_INCREMENT PRIMARY KEY,
                      name VARCHAR(50),
                      age INT
);

# 천만건 데이터 생성
INSERT INTO user (name, age)
SELECT
    CONCAT('user',
           n1.a + n2.a*10 + n3.a*100 + n4.a*1000 + n5.a*10000 + n6.a*100000 + n7.a*1000000 + 1),
    FLOOR(RAND() * 100)
FROM
    (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) n1,
    (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) n2,
    (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) n3,
    (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) n4,
    (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) n5,
    (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) n6,
    (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
     UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) n7;

SELECT COUNT(*) FROM user;

# 인덱스 X
SELECT * FROM user WHERE name = 'user5000';

# 인덱스 O
CREATE INDEX idx_user_name ON user(name);
SELECT * FROM user WHERE name = 'user5000';



# 4-2
# 실습 준비
CREATE TABLE users (
                       id BIGINT PRIMARY KEY,
                       name VARCHAR(50),
                       age INT,
                       city VARCHAR(50),
                       INDEX idx_name (name),
                       INDEX idx_age (age)
);
INSERT INTO users (id, name, age, city)
VALUES
    (1, 'Viva', 30, 'Seoul'),
    (2, 'Ravi', 29, 'Busan'),
    (3, 'Viva', 25, 'Incheon'),
    (4, 'Minho', 30, 'Daegu');

# 실습 1 - Unique Scan (정확한 한 건 탐색)
EXPLAIN FORMAT=TRADITIONAL SELECT * FROM users WHERE id = 1;

# 실습 2 - Range Scan (범위 탐색)
EXPLAIN FORMAT=TRADITIONAL SELECT * FROM users WHERE age BETWEEN 20 AND 30;

# 실습 3 - Table Full Scan (인덱스 없는 컬럼 탐색)
EXPLAIN FORMAT=TRADITIONAL SELECT * FROM users WHERE city = 'Seoul';